services:
  - type: web
    name: news-management-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: FLASK_ENV
        value: production
